import { auth } from "@auth";
import { taskService } from "@/server/services/taskService";
import { goalService } from "@/server/services/goalService";
import { llmClient } from "@/server/llmClient";
import { NextResponse } from "next/server";
import { handleRouteError } from "@/lib/routeError";
import { z } from "zod";

const DailyPlanRequestSchema = z.object({
  timeAvailable: z.number().int().min(30).max(1440).default(480),
  constraints: z.array(z.string().max(200)).max(10).default([]),
  notes: z.string().max(1000).default(""),
});

// Input: user context (timeAvailable, energyLevel, constraints, notes)
// Output: DailyPlan JSON generated by AI
export async function POST(request: Request) {
  const session = await auth();
  const userId = session?.user?.email;
  if (!userId) {
    return new NextResponse("Unauthorized", { status: 401 });
  }

  try {
    const body = await request.json();
    const parsed = DailyPlanRequestSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: "Validation failed", details: parsed.error.flatten() },
        { status: 400 }
      );
    }
    const { timeAvailable, constraints, notes } = parsed.data;

    const today = new Date().toISOString().split("T")[0];

    // 1. Fetch context
    const existingTasks = await taskService.getTasks(userId, { date: today });
    const activeGoals = await goalService.getGoals(userId, { archived: false });

    // 2. Call LLM
    const plan = await llmClient.generateDailyPlan({
      date: today,
      timeAvailableMinutes: timeAvailable,
      constraints,
      notes,
      existingTasks,
      activeGoals,
    });

    return NextResponse.json(plan);
  } catch (error: unknown) {
    console.error("Plan API Error:", error);
    return handleRouteError(error);
  }
}
