import { auth } from "@auth";
import { taskService } from "@/server/services/taskService";
import { goalService } from "@/server/services/goalService";
import { llmClient } from "@/server/llmClient";
import { NextResponse } from "next/server";
import { Goal } from "@/core/planTypes";
import { handleRouteError } from "@/lib/routeError";

// Input: user context (timeAvailable, energyLevel, constraints, notes)
// Output: DailyPlan JSON generated by AI
export async function POST(request: Request) {
  const session = await auth();
  const userId = session?.user?.email;
  if (!userId) {
    return new NextResponse("Unauthorized", { status: 401 });
  }

  try {
    const body = await request.json();
    const { timeAvailable = 480, constraints = [], notes = "" } = body;

    const today = new Date().toISOString().split("T")[0];

    // 1. Fetch context
    const existingTasks = await taskService.getTasks(userId, { date: today });
    const activeGoals = await goalService.getGoals(userId, { archived: false });

    // 2. Call LLM
    const plan = await llmClient.generateDailyPlan({
      date: today,
      timeAvailableMinutes: timeAvailable,
      constraints,
      notes,
      existingTasks,
      activeGoals,
    });

    return NextResponse.json(plan);
  } catch (error: unknown) {
    console.error("Plan API Error:", error);
    const message = error instanceof Error ? error.message : "An unknown error occurred";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
